#!/usr/bin/env bash

set -e
BIN=$(readlink -f ../builddir)

cd encode-wrap

$VALGRIND "$BIN"/brr_encoder \
    encode-wrap.wav \
    encode-wrap.brr \
    2>&1 | tee encode.txt

$VALGRIND "$BIN"/brr_decoder \
    encode-wrap.brr \
    decoded.wav \
    2>&1 | tee decode.txt
