#!/usr/bin/env bash

set -e
source setup-test-env.sh

cd loop

for x in n l s c b; do
    $VALGRIND "$BIN"/brr_encoder -l48 -r${x}0.5 loop.wav loop-${x}.brr
    $VALGRIND "$BIN"/brr_decoder loop-${x}.brr loop-${x}.wav
done
