#!/usr/bin/env bash

# Test brr_encoder with an aliased saw wave designed to benefit from wrapping.

BIN=$(readlink -f ../builddir)

cd encode-wrap-real || exit

# no -w
valgrind "$BIN"/brr_encoder \
    saw15.wav \
    saw15.brr \
    2>&1 | tee encode.txt

valgrind "$BIN"/brr_decoder \
    saw15.brr \
    saw15-brrtools.wav \
    2>&1 | tee decode.txt

wine ../snesbrr.exe -d saw15.brr saw15-snesbrr.wav

# -w
valgrind "$BIN"/brr_encoder -w \
    saw15.wav \
    saw15-w.brr \
    2>&1 | tee encode-w.txt

valgrind "$BIN"/brr_decoder \
    saw15-w.brr \
    saw15-w-brrtools.wav \
    2>&1 | tee decode-w.txt

wine ../snesbrr.exe -d saw15-w.brr saw15-w-snesbrr.wav

