#!/usr/bin/env bash

BIN=$(readlink -f ../builddir)

cd timecop || exit

# previously generated a wrapping .brr file
valgrind "$BIN"/brr_encoder -g reference.wav reencode.brr

# correctly decodes file
valgrind "$BIN"/brr_decoder reencode.brr reencode.wav
# outputs identical .wav file
wine ../snesbrr.exe -d reencode.brr reencode-ref.wav
