#!/usr/bin/env bash

set -e
BIN=$(readlink -f ../builddir)

cd loop

valgrind --error-exitcode=128 "$BIN"/brr_encoder -l48 -H \
    loop.wav \
    loop.brr

valgrind --error-exitcode=128 "$BIN"/brr_decoder \
    loop.brr \
    decoded.wav

valgrind --error-exitcode=128 "$BIN"/brr_decoder -n2 \
    loop.brr \
    decoded2.wav
