#!/usr/bin/env bash

set -e
source setup-test-env.sh

cd loop

$VALGRIND "$BIN"/brr_encoder -l48 -H \
    loop.wav \
    loop.brr

$VALGRIND "$BIN"/brr_decoder \
    loop.brr \
    decoded.wav

$VALGRIND "$BIN"/brr_decoder -n2 \
    loop.brr \
    decoded2.wav
